### ISSUE TITLE
Win binary not working

### ISSUE THREAD

**Issue by crisdosaygo** [i5ik/jspaint.exe#4]
Need to investigate.

**Comment by crisdosaygo** [comment]
Just donwloaded from release page but it fails. Why?

**Comment by crisdosaygo** [comment]
Seems issue is with updates to both chrome as well as Node. 

Experimented with switching everything to ES modules but nexe doesn't support that yet and I don't want to go with no-cross-compile-but-otherwise-promising caxa.

So will switch back to CJS but on windows at least I get a bug

```
TypeError [ERR_INVALID_FILE_URL_PATH]: File URL path must be absolute
    at getPathFromURLWin32 (internal/url.js:1352:11)
    at fileURLToPath (internal/url.js:1382:22)
    at eval (webpack://@my-user-name/my-app/./src/lib/common.js?:38:141)
    at Module../src/lib/common.js (file:///C:/Users/cris7/Downloads/grader.mjs:489:1)
....
```

**Comment by crisdosaygo** [comment]
I have an error transcript. Should be possible to fix
